project:
  type: website

website:
  title: "The Bioinformatics Toolkit"
  navbar:
    logo: icon.png
    left:
      - href: index.qmd
        text: Home
      - href: javascript.qmd
        text: Javascript
      - href: fastx.qmd
        text: fastx

format:
  html:
    self-contained: true
    theme: cosmo
    css: styles.css
    toc: true



