name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          npm install

      - name: install dependencies (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          npm install


      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'BioinformaticsToolkit v__VERSION__'
          releaseBody: 'Release of the Bioinformaticstoolkit using Github Actions'
          releaseDraft: true
          prerelease: false
          tauriScript: "cargo tauri build"

