name: 'test-on-pr'
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        # platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf wget
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb
      - name: install dependencies (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install quarto
      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          brew install quarto
          
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload macOS installer artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: macOS Installer (${{ matrix.os }})
      #     path: "./out/macos-universal/crc-macos-installer.pkg"
      # - name: Install crc pkg
      #   run: sudo installer -pkg out/macos-universal/crc-macos-installer.pkg -target /